import React from 'react';
import {
  Maximize2,
  Minimize2,
  Crop,
  RotateCw,
  RefreshCw,
  FileText,
  FileImage,
  Layers,
  Scissors,
  Braces,
  CheckCircle,
  Minimize,
  Binary,
  Link,
  Key,
  Code,
  FileCode,
  Terminal,
  Database,
  QrCode,
  Hash,
  CaseSensitive,
  ListFilter,
  Sparkles,
  ArrowUpDown,
  Search,
  Percent,
  Calendar,
  Tag,
  TrendingUp,
  DollarSign,
  Clock,
  Ruler,
  Scale,
  Thermometer,
  HardDrive,
  Calculator,
  Type,
  Image as ImgIcon,
  HelpCircle,
  Heart,
  ExternalLink,
  Download,
  Copy,
  Trash2,
  Play,
  RotateCcw,
  Sliders,
  Check,
  ChevronRight,
  ChevronDown,
  Moon,
  Sun,
  Globe,
  Share2,
  Shield,
  Zap,
  UserX,
  Lock,
  ArrowRight,
  Eye,
  Plus,
  ArrowLeft,
  Star,
  Flame,
  Wand2,
} from 'lucide-react';

const iconMap: Record<string, React.ElementType> = {
  Maximize2Icon: Maximize2,
  Minimize2Icon: Minimize2,
  CropIcon: Crop,
  RotateCwIcon: RotateCw,
  RefreshCwIcon: RefreshCw,
  FileTextIcon: FileText,
  FileImageIcon: FileImage,
  LayersIcon: Layers,
  ScissorsIcon: Scissors,
  BracesIcon: Braces,
  CheckCircleIcon: CheckCircle,
  MinimizeIcon: Minimize,
  BinaryIcon: Binary,
  LinkIcon: Link,
  KeyIcon: Key,
  CodeIcon: Code,
  FileCodeIcon: FileCode,
  TerminalIcon: Terminal,
  DatabaseIcon: Database,
  QrCodeIcon: QrCode,
  HashIcon: Hash,
  CaseSensitiveIcon: CaseSensitive,
  ListFilterIcon: ListFilter,
  SparklesIcon: Sparkles,
  ArrowUpDownIcon: ArrowUpDown,
  SearchIcon: Search,
  PercentIcon: Percent,
  CalendarIcon: Calendar,
  TagIcon: Tag,
  TrendingUpIcon: TrendingUp,
  DollarSignIcon: DollarSign,
  ClockIcon: Clock,
  RulerIcon: Ruler,
  ScaleIcon: Scale,
  ThermometerIcon: Thermometer,
  HardDriveIcon: HardDrive,
  CalculatorIcon: Calculator,
  TypeIcon: Type,
  ImageIcon: ImgIcon,
};

interface ToolIconProps {
  name: string;
  className?: string;
}

export const ToolIcon: React.FC<ToolIconProps> = ({ name, className = 'w-5 h-5' }) => {
  const IconComponent = iconMap[name] || FileText;
  return <IconComponent className={className} />;
};

export {
  Maximize2,
  Minimize2,
  Crop,
  RotateCw,
  RefreshCw,
  FileText,
  FileImage,
  Layers,
  Scissors,
  Braces,
  CheckCircle,
  Minimize,
  Binary,
  Link,
  Key,
  Code,
  FileCode,
  Terminal,
  Database,
  QrCode,
  Hash,
  CaseSensitive,
  ListFilter,
  Sparkles,
  ArrowUpDown,
  Search,
  Percent,
  Calendar,
  Tag,
  TrendingUp,
  DollarSign,
  Clock,
  Ruler,
  Scale,
  Thermometer,
  HardDrive,
  Calculator,
  Type,
  ImgIcon as ImageIcon,
  HelpCircle,
  Heart,
  ExternalLink,
  Download,
  Copy,
  Trash2,
  Play,
  RotateCcw,
  Sliders,
  Check,
  ChevronRight,
  ChevronDown,
  Moon,
  Sun,
  Globe,
  Share2,
  Shield,
  Zap,
  UserX,
  Lock,
  ArrowRight,
  Eye,
  Plus,
  ArrowLeft,
  Star,
  Flame,
  Wand2,
};
